<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Descriptive Statistics / Applying functions to columns of data | Statistical Reasoning through Computation and R</title>
  <meta name="description" content="Chapter 3 Descriptive Statistics / Applying functions to columns of data | Statistical Reasoning through Computation and R" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Descriptive Statistics / Applying functions to columns of data | Statistical Reasoning through Computation and R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="true" />
  
  
  <meta name="github-repo" content="lebebr01/stat_thinking" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Descriptive Statistics / Applying functions to columns of data | Statistical Reasoning through Computation and R" />
  
  
  

<meta name="author" content="Brandon LeBeau and Andrew S. Zieffler" />


<meta name="date" content="2019-09-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="visualization.html"/>
<link rel="next" href="multivariate-visualization.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Reasoning through Computation and R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#statistics-vs-data-science"><i class="fa fa-check"></i><b>1.1</b> Statistics vs Data Science</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#experiments-vs-observations"><i class="fa fa-check"></i><b>1.2</b> Experiments vs Observations</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#data-structure"><i class="fa fa-check"></i><b>1.3</b> Data Structure</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i><b>2</b> Visualization</a><ul>
<li class="chapter" data-level="2.0.1" data-path="visualization.html"><a href="visualization.html#college-scorecard-data"><i class="fa fa-check"></i><b>2.0.1</b> College Scorecard Data</a></li>
<li class="chapter" data-level="2.0.2" data-path="visualization.html"><a href="visualization.html#view-the-data"><i class="fa fa-check"></i><b>2.0.2</b> View the Data</a></li>
<li class="chapter" data-level="2.1" data-path="visualization.html"><a href="visualization.html#exploring-attributes"><i class="fa fa-check"></i><b>2.1</b> Exploring Attributes</a><ul>
<li class="chapter" data-level="2.1.1" data-path="visualization.html"><a href="visualization.html#histograms"><i class="fa fa-check"></i><b>2.1.1</b> Histograms</a></li>
<li class="chapter" data-level="2.1.2" data-path="visualization.html"><a href="visualization.html#interpretting-histograms"><i class="fa fa-check"></i><b>2.1.2</b> Interpretting Histograms</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="visualization.html"><a href="visualization.html#plot-customization"><i class="fa fa-check"></i><b>2.2</b> Plot Customization</a><ul>
<li class="chapter" data-level="2.2.1" data-path="visualization.html"><a href="visualization.html#axes-labels"><i class="fa fa-check"></i><b>2.2.1</b> Axes labels</a></li>
<li class="chapter" data-level="2.2.2" data-path="visualization.html"><a href="visualization.html#plot-title-and-subtitle"><i class="fa fa-check"></i><b>2.2.2</b> Plot title and subtitle</a></li>
<li class="chapter" data-level="2.2.3" data-path="visualization.html"><a href="visualization.html#plot-theme"><i class="fa fa-check"></i><b>2.2.3</b> Plot theme</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="visualization.html"><a href="visualization.html#density-plots"><i class="fa fa-check"></i><b>2.3</b> Density plots</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics / Applying functions to columns of data</a><ul>
<li class="chapter" data-level="3.1" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#applying-functions-to-data"><i class="fa fa-check"></i><b>3.1</b> Applying Functions to Data</a></li>
<li class="chapter" data-level="3.2" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#setup"><i class="fa fa-check"></i><b>3.2</b> Setup</a><ul>
<li class="chapter" data-level="3.2.1" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#loading-r-packages"><i class="fa fa-check"></i><b>3.2.1</b> Loading R packages</a></li>
<li class="chapter" data-level="3.2.2" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#read-in-data"><i class="fa fa-check"></i><b>3.2.2</b> Read in Data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#functions-to-columns-of-data"><i class="fa fa-check"></i><b>3.3</b> Functions to columns of data</a></li>
<li class="chapter" data-level="3.4" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#considering-groups"><i class="fa fa-check"></i><b>3.4</b> Considering Groups</a><ul>
<li class="chapter" data-level="3.4.1" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#adding-additional-groups"><i class="fa fa-check"></i><b>3.4.1</b> Adding additional groups</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#other-statistics-of-center"><i class="fa fa-check"></i><b>3.5</b> Other statistics of center</a></li>
<li class="chapter" data-level="3.6" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#measures-of-variation"><i class="fa fa-check"></i><b>3.6</b> Measures of Variation</a><ul>
<li class="chapter" data-level="3.6.1" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#robust-measure-of-variation"><i class="fa fa-check"></i><b>3.6.1</b> Robust measure of variation</a></li>
<li class="chapter" data-level="3.6.2" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#variation-by-group"><i class="fa fa-check"></i><b>3.6.2</b> Variation by Group</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="descriptive-statistics-applying-functions-to-columns-of-data.html"><a href="descriptive-statistics-applying-functions-to-columns-of-data.html#other-measures-of-variation"><i class="fa fa-check"></i><b>3.7</b> Other measures of variation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multivariate-visualization.html"><a href="multivariate-visualization.html"><i class="fa fa-check"></i><b>4</b> Multivariate Visualization</a><ul>
<li class="chapter" data-level="4.1" data-path="multivariate-visualization.html"><a href="multivariate-visualization.html#facetting"><i class="fa fa-check"></i><b>4.1</b> Facetting</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification</a><ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#topic-decision-trees---bar-charts-of-percentage-of-correct-classification"><i class="fa fa-check"></i><b>5.1</b> Topic: Decision Trees - bar charts of percentage of correct classification</a><ul>
<li class="chapter" data-level="5.1.1" data-path="classification.html"><a href="classification.html#performance-measures"><i class="fa fa-check"></i><b>5.1.1</b> Performance Measures</a></li>
<li class="chapter" data-level="5.1.2" data-path="classification.html"><a href="classification.html#comparison-to-baseline"><i class="fa fa-check"></i><b>5.1.2</b> Comparison to Baseline</a></li>
<li class="chapter" data-level="5.1.3" data-path="classification.html"><a href="classification.html#overfitting"><i class="fa fa-check"></i><b>5.1.3</b> Overfitting</a></li>
<li class="chapter" data-level="5.1.4" data-path="classification.html"><a href="classification.html#cross-validation"><i class="fa fa-check"></i><b>5.1.4</b> Cross-validation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-model.html"><a href="linear-model.html"><i class="fa fa-check"></i><b>6</b> Linear Model</a><ul>
<li class="chapter" data-level="6.1" data-path="linear-model.html"><a href="linear-model.html#simple-regression-continuous-predictor"><i class="fa fa-check"></i><b>6.1</b> Simple Regression continuous predictor</a></li>
<li class="chapter" data-level="6.2" data-path="linear-model.html"><a href="linear-model.html#conditional-means"><i class="fa fa-check"></i><b>6.2</b> Conditional Means</a></li>
<li class="chapter" data-level="6.3" data-path="linear-model.html"><a href="linear-model.html#categorical-predictors"><i class="fa fa-check"></i><b>6.3</b> Categorical Predictor(s)</a></li>
<li class="chapter" data-level="6.4" data-path="linear-model.html"><a href="linear-model.html#multiple-regression"><i class="fa fa-check"></i><b>6.4</b> Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html"><i class="fa fa-check"></i><b>7</b> Estimation / Bootstrap / Uncertainty</a></li>
<li class="chapter" data-level="8" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html"><i class="fa fa-check"></i><b>8</b> Prediction for individuals</a><ul>
<li class="chapter" data-level="8.1" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html#comparison-of-classification-linear-model"><i class="fa fa-check"></i><b>8.1</b> Comparison of classification / linear model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Reasoning through Computation and R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-statistics-applying-functions-to-columns-of-data" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Descriptive Statistics / Applying functions to columns of data</h1>
<div id="applying-functions-to-data" class="section level2">
<h2><span class="header-section-number">3.1</span> Applying Functions to Data</h2>
<p>Data visualization is often the first step on the statistical journey to explore a research question. However, this is usually not where the journey stops, instead additional analyses are often performed to learn more about the average trends seen in the data. These can often be split into two broad categories,</p>
<ol style="list-style-type: decimal">
<li>Descriptive Statistics</li>
<li>Inferential Statistics</li>
</ol>
<p><strong>Descriptive Statistics</strong> help to describe the data and are particularly useful to give a single numeric summary for a single variable. We will explore this idea more fully in this section. <strong>Inferential Statistics</strong> help us to make broader statements from the data we have to the larger group of interest, commonly referred to as the population. More details on these steps later in the course.</p>
</div>
<div id="setup" class="section level2">
<h2><span class="header-section-number">3.2</span> Setup</h2>
<p>We are going to use some real data about higher education institutions from the college scorecard (<a href="https://collegescorecard.ed.gov/" class="uri">https://collegescorecard.ed.gov/</a>) to explore the types of conclusions we can make from the data. The college scorecard releases data on higher education institutions to help make the institutions more transparent and provide a place for parents, students, educators, etc can get information about specific instituations from a third party (i.e. US Department of Education).</p>
<div id="loading-r-packages" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Loading R packages</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre></div>
<pre><code>## ── Attaching packages ────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
## ✔ readr   1.3.1     ✔ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggformula)</code></pre></div>
<pre><code>## Loading required package: ggstance</code></pre>
<pre><code>## 
## Attaching package: &#39;ggstance&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     geom_errorbarh, GeomErrorbarh</code></pre>
<pre><code>## 
## New to ggformula?  Try the tutorials: 
##  learnr::run_tutorial(&quot;introduction&quot;, package = &quot;ggformula&quot;)
##  learnr::run_tutorial(&quot;refining&quot;, package = &quot;ggformula&quot;)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)</code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: mosaicData</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;mosaic&#39;:
##   method                           from   
##   fortify.SpatialPolygonsDataFrame ggplot2</code></pre>
<pre><code>## 
## The &#39;mosaic&#39; package masks several functions from core packages in order to add 
## additional features.  The original behavior of these functions should not be affected by this.
## 
## Note: If you use the Matrix package, be sure to load it BEFORE loading mosaic.</code></pre>
<pre><code>## 
## Attaching package: &#39;mosaic&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:Matrix&#39;:
## 
##     mean</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     count, do, tally</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     cross</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     stat</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     binom.test, cor, cor.test, cov, fivenum, IQR, median,
##     prop.test, quantile, sd, t.test, var</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     max, mean, min, prod, range, sample, sum</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">theme_set</span>(<span class="kw">theme_bw</span>())</code></pre></div>
</div>
<div id="read-in-data" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Read in Data</h3>
<p>The below code will read in the data for us to use in the future. The R function to read in the data is <code>read_csv()</code>. Function arguments are passed within the parentheses and for the <code>read_csv()</code> function the first argument is the path to the data. The data for this example are posted on GitHub in a comma separated file. This means the data is stored in a text format and each variable (i.e. column in the data) is separated by a comma. This is a common format data is stored.</p>
<p>The data is stored to an object named <code>college_score</code>. In R (and other statistical programming languages), it is common to use objects to store results to use later. In this instance, we would like to read in the data and store it to use it later. For example, we will likely want to explore the data visually to see if we can extract some trends from the data. The assignment to an object in R is done with the <code>&lt;-</code> assignment operator. Finally, there is one additional argument, <code>guess_max</code> which helps to ensure that the data are read in appropriately. More on this later.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/lebebr01/statthink/master/data-raw/College-scorecard-clean.csv&quot;</span>, <span class="dt">guess_max =</span> <span class="dv">10000</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   instnm = col_character(),
##   city = col_character(),
##   stabbr = col_character(),
##   preddeg = col_character(),
##   region = col_character(),
##   locale = col_character(),
##   adm_rate = col_double(),
##   actcmmid = col_double(),
##   ugds = col_double(),
##   costt4_a = col_double(),
##   costt4_p = col_double(),
##   tuitionfee_in = col_double(),
##   tuitionfee_out = col_double(),
##   debt_mdn = col_double(),
##   grad_debt_mdn = col_double(),
##   female = col_double()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(college_score)</code></pre></div>
<pre><code>## # A tibble: 6 x 16
##   instnm city  stabbr preddeg region locale adm_rate actcmmid  ugds
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1 Alaba… Norm… AL     Bachel… South… City:…    0.903       18  4824
## 2 Unive… Birm… AL     Bachel… South… City:…    0.918       25 12866
## 3 Unive… Hunt… AL     Bachel… South… City:…    0.812       28  6917
## 4 Alaba… Mont… AL     Bachel… South… City:…    0.979       18  4189
## 5 The U… Tusc… AL     Bachel… South… City:…    0.533       28 32387
## 6 Aubur… Mont… AL     Bachel… South… City:…    0.825       22  4211
## # … with 7 more variables: costt4_a &lt;dbl&gt;, costt4_p &lt;dbl&gt;,
## #   tuitionfee_in &lt;dbl&gt;, tuitionfee_out &lt;dbl&gt;, debt_mdn &lt;dbl&gt;,
## #   grad_debt_mdn &lt;dbl&gt;, female &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="functions-to-columns-of-data" class="section level2">
<h2><span class="header-section-number">3.3</span> Functions to columns of data</h2>
<p>Data are often stored in a tabular format where the rows of the data are the units and the columns in a data frame are the varaibles. This is shown in the college scorecard data above where the rows of the data are specific institutions of higher education and the columns represent various attributes about those higher education institutions. This is a common structure to store data where each row represents a unique unit or measurement occasion for longitudinal data.</p>
<p>In the data visualization units, we accessed columns of data to view the distribution of the particular variable. For example, we explore histograms of admission rate. Instead of visualizing the data, now we will apply functions to these columns to calculate statistics of interest. In particular, the focus will be on the calculating statistics for variables that are numeric rather than representing categories. We will discuss this in more detail as we move along.</p>
<p>Let’s keep talking about the admission rate as we have explored that visually already and start with an example.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, median)</code></pre></div>
<pre><code>##   median_adm_rate
## 1          0.7077</code></pre>
<p>The <code>df_stats()</code> function takes a formula syntax that is similar to the syntax used for viewing a univariate distribution you saw earlier. In particular, the variable that we wish to compute a statistic on is specified after the <code>~</code>. The next argument is the data argument. Finally, subsequent arguments after the data argument are functions that we want to compute for the variable specified. Here, I compute the median which happens to be, 0.708. The median is also referred to as the 50% percentile and is the location where half of the data (in this case higher education institutions) are above and below an admission rate of 70.8%.</p>
<p>Let’s think where this shows up on the admission rate distribution we plotted earlier.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_histogram</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, <span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, median)[[<span class="dv">1</span>]], <span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>You’ll notice that the line is just to the left of the main peak of the data. Does it appear that half of the data are below and half are above the blue line in the figure?</p>
<p>The median is a special percentile, however other percentiles may be of interest. For example, maybe we’d want to know what the 20th percentile is or the 80th percentile to apply to a school that isn’t too selective or is not selective at all. We can compute these with the <code>df_stats()</code> function again.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">q &lt;-<span class="st"> </span>college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="kw">quantile</span>(<span class="kw">c</span>(<span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="fl">0.8</span>)), <span class="dt">nice_names =</span> <span class="ot">TRUE</span>)
q</code></pre></div>
<pre><code>##      X20.   X50.    X80.
## 1 0.51428 0.7077 0.86932</code></pre>
<p>Let’s look where these fall on our distribution.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_histogram</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, <span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>value, <span class="dt">data =</span> <span class="kw">gather</span>(q), <span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Does it appear that 20% of the data are below the first line and 20% are above the last line? Difficult to view on the histogram. An empirical distribution figure, sometimes called an ogive, can be helpful to show these.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_ecdf</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>value, <span class="dt">data =</span> <span class="kw">gather</span>(q), <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_hline</span>(<span class="dt">color =</span> <span class="st">&#39;darkblue&#39;</span>, <span class="dt">yintercept =</span> <span class="op">~</span><span class="kw">c</span>(<span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="fl">0.8</span>), <span class="dt">data =</span> <span class="ot">NA</span>, <span class="dt">linetype =</span> <span class="dv">3</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_labs</span>(<span class="dt">y =</span> <span class="st">&#39;Cumulative proportion&#39;</span>)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Here you can see that the horizontal lines cross over the vertical lines at the specified values (i.e. 20% for the first vertical line, 50% for the second vertical line, 80% for the final vertical line).</p>
</div>
<div id="considering-groups" class="section level2">
<h2><span class="header-section-number">3.4</span> Considering Groups</h2>
<p>We’ve spent a lot of time trying to reason about other variables that may be important in explaining variation in our variable of interest. So far we have only explored the variable without considering other variables, in practice that is not that useful.</p>
<p>Instead, it is common to compute conditional statistics based on other characteristics in the data. An example may help to show the idea more clearly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(adm_rate <span class="op">~</span><span class="st"> </span>region, median)</code></pre></div>
<pre><code>##                region median_adm_rate
## 1            Far West         0.70360
## 2         Great Lakes         0.71110
## 3            Mid East         0.73735
## 4         New England         0.73590
## 5      Outlying Areas         0.81160
## 6              Plains         0.69600
## 7     Rocky Mountains         0.82865
## 8           Southeast         0.65965
## 9           Southwest         0.71220
## 10 US Service Schools         0.10740</code></pre>
<p>Presented above are the conditional medians for the higher education institutions in different areas of the country. More specifically, the data are essentially split into subgroups and the median is computed for each of those subgroups instead of pooling all institutions into a single data frame. The formula syntax is now <code>outcome ~ grouping</code> where the variable of interest (i.e. commonly a numeric variable) and the variable to the right of the <code>~</code> is the grouping variable. This syntax is similar to the violin plots that were created earlier.</p>
<p>Can you see differences in the admission rates across the regions?</p>
<p>One thing that is useful to add in when computing conditional statisics, is how many data points are in each group. This is particularly useful when the groups are different sizes, which is common. To do this, we can add another function to the <code>df_stats()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(adm_rate <span class="op">~</span><span class="st"> </span>region, median, length)</code></pre></div>
<pre><code>##                region median_adm_rate length_adm_rate
## 1            Far West         0.70360             221
## 2         Great Lakes         0.71110             297
## 3            Mid East         0.73735             458
## 4         New England         0.73590             167
## 5      Outlying Areas         0.81160              35
## 6              Plains         0.69600             200
## 7     Rocky Mountains         0.82865              50
## 8           Southeast         0.65965             454
## 9           Southwest         0.71220             133
## 10 US Service Schools         0.10740               4</code></pre>
<p>This adds another columns which represents the number of observations that went into the median calculation for each group. The syntax above also shows that you can add additional functions separated by a comma in the <code>df_stats()</code> function and are not limited to a single function. We will take advantage of this feature later on.</p>
<div id="adding-additional-groups" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Adding additional groups</h3>
<p>What if we thought more than one variable was important in explaining variation in the outcome variable? These can also be added to the <code>df_stats()</code> function for additional conditional statistics. The key is to add another variable to the right-hand side of the formula argument. More than one variable are separated with a <code>+</code> symbol.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(adm_rate <span class="op">~</span><span class="st"> </span>region <span class="op">+</span><span class="st"> </span>preddeg, median, length)</code></pre></div>
<pre><code>##                region            preddeg median_adm_rate length_adm_rate
## 1            Far West   Associate Degree         0.58935              12
## 2         Great Lakes   Associate Degree         0.79515              22
## 3            Mid East   Associate Degree         0.80290              54
## 4         New England   Associate Degree         0.78430               7
## 5      Outlying Areas   Associate Degree         0.87040               6
## 6              Plains   Associate Degree         0.74610               8
## 7     Rocky Mountains   Associate Degree         0.83970               5
## 8           Southeast   Associate Degree         0.72525              34
## 9           Southwest   Associate Degree         0.42260               5
## 10           Far West    Bachelor Degree         0.69260             172
## 11        Great Lakes    Bachelor Degree         0.70560             252
## 12           Mid East    Bachelor Degree         0.70790             340
## 13        New England    Bachelor Degree         0.72980             145
## 14     Outlying Areas    Bachelor Degree         0.70905              24
## 15             Plains    Bachelor Degree         0.68330             173
## 16    Rocky Mountains    Bachelor Degree         0.82865              40
## 17          Southeast    Bachelor Degree         0.64180             393
## 18          Southwest    Bachelor Degree         0.71975             116
## 19 US Service Schools    Bachelor Degree         0.10740               4
## 20           Far West Certificate Degree         0.76470              37
## 21        Great Lakes Certificate Degree         0.83960              23
## 22           Mid East Certificate Degree         0.79505              64
## 23        New England Certificate Degree         0.81820              15
## 24     Outlying Areas Certificate Degree         1.00000               5
## 25             Plains Certificate Degree         0.82140              19
## 26    Rocky Mountains Certificate Degree         0.67200               5
## 27          Southeast Certificate Degree         0.75700              27
## 28          Southwest Certificate Degree         0.72365              12</code></pre>
</div>
</div>
<div id="other-statistics-of-center" class="section level2">
<h2><span class="header-section-number">3.5</span> Other statistics of center</h2>
<p>So far we have been discussing the median. The median attempts to provide a single number summary for the center of the distribution. It is a robust statistic, but likely isn’t the most popular statistic to provide a location for the center of a distribution. The mean is often more commonly used as a measure of the center of a distribution. Part of this is due to the usage of the mean in common statistical methods and the mean also uses the values of all the data in the calculation. The median only considers the values of the middle score or scores, therefore this statistic is less sensitive to extreme values than the mean. I like to look at both statistics and this can provide some insight into the distribution of interest. We can add the mean using the <code>df_stats()</code> function by adding the function <code>mean</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats_compute &lt;-<span class="st"> </span>college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(adm_rate <span class="op">~</span><span class="st"> </span>region, median, mean, length)
stats_compute</code></pre></div>
<pre><code>##                region median_adm_rate mean_adm_rate length_adm_rate
## 1            Far West         0.70360     0.6682570             221
## 2         Great Lakes         0.71110     0.7015263             297
## 3            Mid East         0.73735     0.6920234             458
## 4         New England         0.73590     0.6672838             167
## 5      Outlying Areas         0.81160     0.7885600              35
## 6              Plains         0.69600     0.7000135             200
## 7     Rocky Mountains         0.82865     0.7800680              50
## 8           Southeast         0.65965     0.6560097             454
## 9           Southwest         0.71220     0.6696759             133
## 10 US Service Schools         0.10740     0.1302000               4</code></pre>
<p>Do you notice any trends in the direction the mean and median typically follow? More specifically, is the mean typically larger than the median or vice versa?</p>
<p>Let’s visualize them.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_histogram</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, <span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_facet_wrap</span>(<span class="op">~</span><span class="st"> </span>region) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>median_adm_rate, <span class="dt">data =</span> stats_compute, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;lightblue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>mean_adm_rate, <span class="dt">data =</span> stats_compute, <span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>What is different about the distributions that have larger differences in the mean and median?</p>
</div>
<div id="measures-of-variation" class="section level2">
<h2><span class="header-section-number">3.6</span> Measures of Variation</h2>
<p>So far we have focused primarily on applying functions to columns of data to provide a single numeric summary for where the center of the distribution may lie. The center of the distribution is important, however the primary goal in research and with statistics is to try to understand the variation in the distribution.</p>
<p>One crude measure of variation that is intuitive is the range of a variable. The range is the difference between the smallest and the largest number in the data. We can compute this with the <code>df_stats()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, range)</code></pre></div>
<pre><code>##   range_adm_rate_1 range_adm_rate_2
## 1                0                1</code></pre>
<p>The details of the <code>df_stats()</code> function are in the previous course notes. The output for this computation returns two values, the minimum and maximum value in the data and unsurprisingly, is 0 and 1 respectively. The range is most useful as a data checking process to ensure that the variable contains values that are theoretically possible, which is true in this case. The range is known as a biased statistic in that it will almost always be smaller than the population value. Therefore, we would like a better statistic for measures of variation.</p>
<div id="robust-measure-of-variation" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Robust measure of variation</h3>
<p>A robust measure of variation that often is used in tandem with the median is the interquartile range (IQR). This statistic can be calculated in two ways, either using the <code>IQR()</code> or <code>quantile()</code> function. Both are presented below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, IQR, <span class="kw">quantile</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>)), <span class="dt">nice_names =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>##   IQR_adm_rate   X25.    X75.
## 1      0.28575 0.5524 0.83815</code></pre>
<p>The IQR is the difference between the 75th and 25th percentiles and in this example equals 0.285 or about 28.5%. As the IQR represents differences in percentiles, we could say that the middle 50% of the distribution is found between 55% and 84% and the middle 50% is spread out by about 28.5%. The idea behind the IQR representing differences in percentiles allows us to extend this to different percentiles that may be more directly interpretable for a given situation. For example, suppose we wanted to know how spread out the middle 80% of the distribution is. We can do this directly by computing the 90th and 10th percentiles and finding the difference between the two.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mid_<span class="dv">80</span> &lt;-<span class="st"> </span>college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="kw">quantile</span>(<span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>)), <span class="dt">nice_names =</span> <span class="ot">TRUE</span>)
mid_<span class="dv">80</span></code></pre></div>
<pre><code>##      X10.    X90.
## 1 0.39284 0.94706</code></pre>
<p>As you can see, once you extend the amount of the distribution contained, the distance increases, now to 0.555 or 55.5% the the range of the middle 80% of the admission rate distribution. We can also visualize what this looks like.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_histogram</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&#39;black&#39;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>value, <span class="dt">data =</span> <span class="kw">gather</span>(mid_<span class="dv">80</span>), <span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>We can also view the exact percentages using the empirical cumulative density function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_ecdf</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>value, <span class="dt">data =</span> <span class="kw">gather</span>(mid_<span class="dv">80</span>), <span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="variation-by-group" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Variation by Group</h3>
<p>These statistics can also be calculated by different grouping variables similar to what was done with statisitcs of center. Now the variable of interest is on the left-hand side of the equation and the grouping variable is on the right hand side.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">iqr_groups &lt;-<span class="st"> </span>college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(adm_rate <span class="op">~</span><span class="st"> </span>region, IQR, <span class="kw">quantile</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>)), <span class="dt">nice_names =</span> <span class="ot">TRUE</span>)
iqr_groups</code></pre></div>
<pre><code>##                region IQR_adm_rate    X25.     X75.
## 1            Far West     0.306700 0.52480 0.831500
## 2         Great Lakes     0.220300 0.60580 0.826100
## 3            Mid East     0.279425 0.57140 0.850825
## 4         New England     0.288000 0.54525 0.833250
## 5      Outlying Areas     0.318600 0.64135 0.959950
## 6              Plains     0.272200 0.56990 0.842100
## 7     Rocky Mountains     0.281950 0.64590 0.927850
## 8           Southeast     0.286950 0.52525 0.812200
## 9           Southwest     0.311400 0.51900 0.830400
## 10 US Service Schools     0.052000 0.09280 0.144800</code></pre>
<p>This can also be visualized to see how these statistics vary across the groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_histogram</span>(<span class="op">~</span><span class="st"> </span>adm_rate, <span class="dt">data =</span> college_score, <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&#39;black&#39;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_vline</span>(<span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xintercept =</span> <span class="op">~</span><span class="st"> </span>value, 
     <span class="dt">data =</span> <span class="kw">filter</span>(<span class="kw">pivot_longer</span>(iqr_groups, IQR_adm_rate<span class="op">:</span><span class="st">&#39;X75.&#39;</span>), name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;X25.&#39;</span>, <span class="st">&#39;X75.&#39;</span>)), <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_facet_wrap</span>(<span class="op">~</span><span class="st"> </span>region)</code></pre></div>
<p><img src="03-descriptive_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
</div>
<div id="other-measures-of-variation" class="section level2">
<h2><span class="header-section-number">3.7</span> Other measures of variation</h2>
<p>There are many other variation measures that are used in statistics. We will apply a functional approach to these and try to visualize what they are trying to represent. The statistics discussed here represent deviations from the mean, either the average absolute deviation or the average squared deviation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, sd, var)</code></pre></div>
<pre><code>##   sd_adm_rate var_adm_rate
## 1   0.2113571   0.04467182</code></pre>
<p>In order to compute the mean absolute error, we first need to define a new function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mae &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, ...) {
  avg &lt;-<span class="st"> </span><span class="kw">mean</span>(x, <span class="dt">na.rm =</span> na.rm, ...)
  abs_avg &lt;-<span class="st"> </span><span class="kw">abs</span>(x <span class="op">-</span><span class="st"> </span>avg)
  
  <span class="kw">mean</span>(abs_avg)
} </code></pre></div>
<p>We can now use this new function just like any other function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">college_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>adm_rate, sd, var, mae)</code></pre></div>
<pre><code>##   sd_adm_rate var_adm_rate mae_adm_rate
## 1   0.2113571   0.04467182    0.1692953</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visualization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multivariate-visualization.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
