<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Linear Model | Statistical Reasoning through Computation and R</title>
  <meta name="description" content="Chapter 6 Linear Model | Statistical Reasoning through Computation and R" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Linear Model | Statistical Reasoning through Computation and R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="true" />
  
  
  <meta name="github-repo" content="lebebr01/stat_thinking" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Linear Model | Statistical Reasoning through Computation and R" />
  
  
  

<meta name="author" content="Brandon LeBeau and Andrew S. Zieffler" />


<meta name="date" content="2020-01-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="classification.html"/>
<link rel="next" href="estimation-bootstrap-uncertainty.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Reasoning through Computation and R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#statistics-vs-data-science"><i class="fa fa-check"></i><b>1.1</b> Statistics vs Data Science</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#experiments-vs-observations"><i class="fa fa-check"></i><b>1.2</b> Experiments vs Observations</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#data-structure"><i class="fa fa-check"></i><b>1.3</b> Data Structure</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i><b>2</b> Visualization</a><ul>
<li class="chapter" data-level="2.0.1" data-path="visualization.html"><a href="visualization.html#college-scorecard-data"><i class="fa fa-check"></i><b>2.0.1</b> College Scorecard Data</a></li>
<li class="chapter" data-level="2.0.2" data-path="visualization.html"><a href="visualization.html#view-the-data"><i class="fa fa-check"></i><b>2.0.2</b> View the Data</a></li>
<li class="chapter" data-level="2.1" data-path="visualization.html"><a href="visualization.html#exploring-attributes"><i class="fa fa-check"></i><b>2.1</b> Exploring Attributes</a><ul>
<li class="chapter" data-level="2.1.1" data-path="visualization.html"><a href="visualization.html#histograms"><i class="fa fa-check"></i><b>2.1.1</b> Histograms</a></li>
<li class="chapter" data-level="2.1.2" data-path="visualization.html"><a href="visualization.html#interpretting-histograms"><i class="fa fa-check"></i><b>2.1.2</b> Interpretting Histograms</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="visualization.html"><a href="visualization.html#plot-customization"><i class="fa fa-check"></i><b>2.2</b> Plot Customization</a><ul>
<li class="chapter" data-level="2.2.1" data-path="visualization.html"><a href="visualization.html#axes-labels"><i class="fa fa-check"></i><b>2.2.1</b> Axes labels</a></li>
<li class="chapter" data-level="2.2.2" data-path="visualization.html"><a href="visualization.html#plot-title-and-subtitle"><i class="fa fa-check"></i><b>2.2.2</b> Plot title and subtitle</a></li>
<li class="chapter" data-level="2.2.3" data-path="visualization.html"><a href="visualization.html#plot-theme"><i class="fa fa-check"></i><b>2.2.3</b> Plot theme</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="visualization.html"><a href="visualization.html#density-plots"><i class="fa fa-check"></i><b>2.3</b> Density plots</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics: Numerically Describing the Sample Data</a><ul>
<li class="chapter" data-level="3.1" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#summarizing-attributes"><i class="fa fa-check"></i><b>3.1</b> Summarizing Attributes</a></li>
<li class="chapter" data-level="3.2" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#understanding-the-median-and-mean"><i class="fa fa-check"></i><b>3.2</b> Understanding the Median and Mean</a><ul>
<li class="chapter" data-level="3.2.1" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#summarize-with-the-mean-or-median"><i class="fa fa-check"></i><b>3.2.1</b> Summarize with the Mean or Median?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#numerically-summarizing-variation"><i class="fa fa-check"></i><b>3.3</b> Numerically Summarizing Variation</a><ul>
<li class="chapter" data-level="3.3.1" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#range"><i class="fa fa-check"></i><b>3.3.1</b> Range</a></li>
<li class="chapter" data-level="3.3.2" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#percentile-range"><i class="fa fa-check"></i><b>3.3.2</b> Percentile Range</a></li>
<li class="chapter" data-level="3.3.3" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#interquartile-range-iqr"><i class="fa fa-check"></i><b>3.3.3</b> Interquartile Range (IQR)</a></li>
<li class="chapter" data-level="3.3.4" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#empirical-cumulative-density"><i class="fa fa-check"></i><b>3.3.4</b> Empirical Cumulative Density</a></li>
<li class="chapter" data-level="3.3.5" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#variance-and-standard-deviation"><i class="fa fa-check"></i><b>3.3.5</b> Variance and Standard Deviation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#summarizing-categorical-attributes"><i class="fa fa-check"></i><b>3.4</b> Summarizing Categorical Attributes</a></li>
<li class="chapter" data-level="3.5" data-path="descriptive-statistics-numerically-describing-the-sample-data.html"><a href="descriptive-statistics-numerically-describing-the-sample-data.html#advanced-extension-computing-your-own-measure-of-variation"><i class="fa fa-check"></i><b>3.5</b> Advanced Extension: Computing Your Own Measure of Variation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multivariate-visualization.html"><a href="multivariate-visualization.html"><i class="fa fa-check"></i><b>4</b> Multivariate Visualization</a><ul>
<li class="chapter" data-level="4.1" data-path="multivariate-visualization.html"><a href="multivariate-visualization.html#facetting"><i class="fa fa-check"></i><b>4.1</b> Facetting</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification</a><ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#topic-decision-trees"><i class="fa fa-check"></i><b>5.1</b> Topic: Decision Trees</a><ul>
<li class="chapter" data-level="5.1.1" data-path="classification.html"><a href="classification.html#fitting-a-classification-tree"><i class="fa fa-check"></i><b>5.1.1</b> Fitting a Classification Tree</a></li>
<li class="chapter" data-level="5.1.2" data-path="classification.html"><a href="classification.html#pruning-trees"><i class="fa fa-check"></i><b>5.1.2</b> Pruning Trees</a></li>
<li class="chapter" data-level="5.1.3" data-path="classification.html"><a href="classification.html#accuracy"><i class="fa fa-check"></i><b>5.1.3</b> Accuracy</a></li>
<li class="chapter" data-level="5.1.4" data-path="classification.html"><a href="classification.html#comparison-to-baseline"><i class="fa fa-check"></i><b>5.1.4</b> Comparison to Baseline</a></li>
<li class="chapter" data-level="5.1.5" data-path="classification.html"><a href="classification.html#trainingtest-data"><i class="fa fa-check"></i><b>5.1.5</b> Training/Test Data</a></li>
<li class="chapter" data-level="5.1.6" data-path="classification.html"><a href="classification.html#introduction-to-resamplingbootstrap"><i class="fa fa-check"></i><b>5.1.6</b> Introduction to resampling/bootstrap</a></li>
<li class="chapter" data-level="5.1.7" data-path="classification.html"><a href="classification.html#cross-validation"><i class="fa fa-check"></i><b>5.1.7</b> Cross-validation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-model.html"><a href="linear-model.html"><i class="fa fa-check"></i><b>6</b> Linear Model</a><ul>
<li class="chapter" data-level="6.1" data-path="linear-model.html"><a href="linear-model.html#regression-trees"><i class="fa fa-check"></i><b>6.1</b> Regression Trees</a><ul>
<li class="chapter" data-level="6.1.1" data-path="linear-model.html"><a href="linear-model.html#visualize-distributions"><i class="fa fa-check"></i><b>6.1.1</b> Visualize distributions</a></li>
<li class="chapter" data-level="6.1.2" data-path="linear-model.html"><a href="linear-model.html#decision-tree---regression-tree"><i class="fa fa-check"></i><b>6.1.2</b> Decision Tree - Regression Tree</a></li>
<li class="chapter" data-level="6.1.3" data-path="linear-model.html"><a href="linear-model.html#evaluating-accuracy"><i class="fa fa-check"></i><b>6.1.3</b> Evaluating accuracy</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="linear-model.html"><a href="linear-model.html#simple-regression-continuous-predictor"><i class="fa fa-check"></i><b>6.2</b> Simple Regression continuous predictor</a><ul>
<li class="chapter" data-level="6.2.1" data-path="linear-model.html"><a href="linear-model.html#description-of-the-data"><i class="fa fa-check"></i><b>6.2.1</b> Description of the Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="linear-model.html"><a href="linear-model.html#scatterplots"><i class="fa fa-check"></i><b>6.2.2</b> Scatterplots</a></li>
<li class="chapter" data-level="6.2.3" data-path="linear-model.html"><a href="linear-model.html#fitting-a-linear-regression-model"><i class="fa fa-check"></i><b>6.2.3</b> Fitting a linear regression model</a></li>
<li class="chapter" data-level="6.2.4" data-path="linear-model.html"><a href="linear-model.html#explore-the-y-intercept"><i class="fa fa-check"></i><b>6.2.4</b> Explore the y-intercept</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="linear-model.html"><a href="linear-model.html#conditional-means"><i class="fa fa-check"></i><b>6.3</b> Conditional Means</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html"><i class="fa fa-check"></i><b>7</b> Estimation / Bootstrap / Uncertainty</a><ul>
<li class="chapter" data-level="7.1" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#estimating-error"><i class="fa fa-check"></i><b>7.1</b> Estimating Error</a></li>
<li class="chapter" data-level="7.2" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#categorical-predictors"><i class="fa fa-check"></i><b>7.2</b> Categorical Predictor(s)</a><ul>
<li class="chapter" data-level="7.2.1" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#mothers-smoking"><i class="fa fa-check"></i><b>7.2.1</b> Mother’s smoking</a></li>
<li class="chapter" data-level="7.2.2" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#linear-regression---categorical-predictor"><i class="fa fa-check"></i><b>7.2.2</b> Linear Regression - Categorical Predictor</a></li>
<li class="chapter" data-level="7.2.3" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#inference"><i class="fa fa-check"></i><b>7.2.3</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#more-than-2-categorical-groups"><i class="fa fa-check"></i><b>7.3</b> More than 2 categorical groups</a><ul>
<li class="chapter" data-level="7.3.1" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#explore-distribution-3-groups"><i class="fa fa-check"></i><b>7.3.1</b> Explore distribution 3 groups</a></li>
<li class="chapter" data-level="7.3.2" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#overall-model-fit"><i class="fa fa-check"></i><b>7.3.2</b> Overall model fit</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#multiple-regression"><i class="fa fa-check"></i><b>7.4</b> Multiple Regression</a><ul>
<li class="chapter" data-level="7.4.1" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#interactions"><i class="fa fa-check"></i><b>7.4.1</b> Interactions</a></li>
<li class="chapter" data-level="7.4.2" data-path="estimation-bootstrap-uncertainty.html"><a href="estimation-bootstrap-uncertainty.html#evaluating-model-fit"><i class="fa fa-check"></i><b>7.4.2</b> Evaluating model fit</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html"><i class="fa fa-check"></i><b>8</b> Prediction for individuals</a><ul>
<li class="chapter" data-level="8.1" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html#comparison-of-classification-linear-model"><i class="fa fa-check"></i><b>8.1</b> Comparison of classification / linear model</a></li>
<li class="chapter" data-level="8.2" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html#compared-linear-model-with-median"><i class="fa fa-check"></i><b>8.2</b> Compared linear model with median</a><ul>
<li class="chapter" data-level="8.2.1" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html#skewed-data---inference"><i class="fa fa-check"></i><b>8.2.1</b> Skewed Data - Inference</a></li>
<li class="chapter" data-level="8.2.2" data-path="prediction-for-individuals.html"><a href="prediction-for-individuals.html#bootstrap-median"><i class="fa fa-check"></i><b>8.2.2</b> Bootstrap Median</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Reasoning through Computation and R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-model" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Linear Model</h1>
<div id="regression-trees" class="section level2">
<h2><span class="header-section-number">6.1</span> Regression Trees</h2>
<p>In this example, data on major league baseball players that comes with an R package, <code>ISLR</code>. These data contain information about hitters in major league baseball for the 1986 season and also contain information about their starting salary for the 1987 season. Missing data related to salary information was dropped from the data. ### Loading R packages hen the packages can be loaded and some processing is done on the <code>Hitters</code> data to drop any missing data elements from the salary data attribute. Finally, the first few rows of the data are shown with the <code>head()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(ggformula)
<span class="kw">library</span>(mosaic)
<span class="kw">library</span>(ISLR)
<span class="kw">library</span>(rpart)
<span class="kw">library</span>(rsample)
<span class="kw">library</span>(rpart.plot)
<span class="kw">library</span>(statthink)

<span class="co"># Set theme for plots</span>
<span class="kw">theme_set</span>(<span class="kw">theme_statthinking</span>())

Hitters &lt;-<span class="st"> </span>Hitters <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">drop_na</span>(Salary)

<span class="kw">head</span>(Hitters)</code></pre></div>
<pre><code>##                   AtBat Hits HmRun Runs RBI Walks Years CAtBat CHits CHmRun
## -Alan Ashby         315   81     7   24  38    39    14   3449   835     69
## -Alvin Davis        479  130    18   66  72    76     3   1624   457     63
## -Andre Dawson       496  141    20   65  78    37    11   5628  1575    225
## -Andres Galarraga   321   87    10   39  42    30     2    396   101     12
## -Alfredo Griffin    594  169     4   74  51    35    11   4408  1133     19
## -Al Newman          185   37     1   23   8    21     2    214    42      1
##                   CRuns CRBI CWalks League Division PutOuts Assists Errors
## -Alan Ashby         321  414    375      N        W     632      43     10
## -Alvin Davis        224  266    263      A        W     880      82     14
## -Andre Dawson       828  838    354      N        E     200      11      3
## -Andres Galarraga    48   46     33      N        E     805      40      4
## -Alfredo Griffin    501  336    194      A        W     282     421     25
## -Al Newman           30    9     24      N        E      76     127      7
##                   Salary NewLeague
## -Alan Ashby        475.0         N
## -Alvin Davis       480.0         A
## -Andre Dawson      500.0         N
## -Andres Galarraga   91.5         N
## -Alfredo Griffin   750.0         A
## -Al Newman          70.0         A</code></pre>
<div id="visualize-distributions" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Visualize distributions</h3>
<p>Exploring the distribution of the variable of interest is often the first step in an analysis. Here, we are interested in exploring the distribution of salaries of major league baseball players and seeing if data attributes can help to predict the salary for the player. The first plot explored is the density of the salary variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_density</span>(<span class="op">~</span><span class="st"> </span>Salary, <span class="dt">data =</span> Hitters)</code></pre></div>
<p><img src="06-regression_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<ol style="list-style-type: decimal">
<li>What are some features of the distribution above?</li>
<li>Could there be some concerns about this distribution if we are looking to do some analysis on this?</li>
</ol>
<p>In general, symmetric distributions are preferred over skewed distributions and some models make an assumption of normality, a special type of symmetric distribution. One way to help make a skewed distribution more symmetric is to transform the data. For a positively skewed distribution, such as income, rent, salary, etc, a log transformation is a common transformation that is used by econometricians and is a meaningful transformation. The largest downside of the transformation is that the original metric is lost and the analysis is done on the transformed metric. The log transformation identified above is often referred to as a non-linear transformation such that it alters values differently based on where these are on the scale. For example, the log transformation will minimize gaps that are higher up on the scale and spread out gaps in small values, this is why this type of transformation is common for right or positively skewed data. Below is a figure applying the log transformation to the salary attribute.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_density</span>(<span class="op">~</span><span class="st"> </span><span class="kw">log</span>(Salary), <span class="dt">data =</span> Hitters)</code></pre></div>
<p><img src="06-regression_files/figure-html/unnamed-chunk-2-1.png" width="672" /> ### Explore relationships between two quantitative attributes So far, the course has focused on exploring relationships between a quantitative and various qualitative (i.e. categorical or grouping) attributes. It is also common to want to explore relationships between two quantitative attributes. One way to visualize this type of relationship is with a scatterplot and this can be done with the <code>gf_point()</code> function. Similar to other multivariate figures, this function takes a formula as the input where the attribute of interest (log of salary here) is placed on the left hand side of the equation and the second attribute is placed on the right hand side of the equation. Below, the equation <code>log(Salary) ~ HmRun</code> means that the log salary is the attribute of interest (placed on the y-axis) is going to be plotted in conjunction with the number of home runs the player hit (placed on the x-axis). Let’s look at the figure.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_point</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>HmRun, <span class="dt">data =</span> Hitters)</code></pre></div>
<p><img src="06-regression_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Another measure of association between two attributes is the correlation. This statistic gives a single number summary about the <strong>linear</strong> relationship between two quantitative attributes. The correlation ranges between -1 and +1 where 0 means no relationship. The closer the correlation gets to -1 or +1 indicates a stronger linear relationship between the two attributes. A correlation of -1 means the two attributes are inversely related, more specifically this means that as one goes up the other will tend to decrease. The opposite is true for a correlation of +1 indicating a positive relationship, as one attribute increases the other tends to increase as well.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>HmRun, <span class="dt">data =</span> Hitters)</code></pre></div>
<pre><code>## [1] 0.3398543</code></pre>
</div>
<div id="decision-tree---regression-tree" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Decision Tree - Regression Tree</h3>
<p>Another way to explore the relationship between two quantitative attributes is through the fitting a regression tree. A regression tree is similar to a classification tree, however now the output is a numeric or continuous type variable that takes on many different values. In the classification tree example, the focus in this class was predicting if a case belonged to one of two classes. In this case, the regression tree will predict the numeric variable with many potential values rather than just two.</p>
<p>The syntax for fitting a regression tree is very similar in R compared to the classification tree. The same function, <code>rpart()</code> is used and the function <code>rpart.plot()</code> will be used to visualize the fitted regression tree similar to before. The primary argument to the <code>rpart()</code> function is a formula where the left-hand side is the attribute of interest and the right hand side contains attributes that help predict the outcome. In the example below, the log of salary is the outcome and the number of home runs hit during the previous season is used as the sole continuous attribute used to predict the log of the salary. The data argument is also specified and the only difference here between a classification tree and the regression tree here is the <code>method</code> argument. In the regression tree the method argument should be set to <code>method = 'anova'</code>. This tells the <code>rpart()</code> function that the outcome is numeric and that an anova method should be used in the model fitting. The anova stands for Analysis of Variance and we will discuss this in more detail moving forward.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hit_reg &lt;-<span class="st"> </span><span class="kw">rpart</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>HmRun, <span class="dt">data =</span> Hitters, <span class="dt">method =</span> <span class="st">&quot;anova&quot;</span>)

<span class="kw">rpart.plot</span>(hit_reg, <span class="dt">roundint =</span> <span class="ot">FALSE</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">branch =</span> .<span class="dv">3</span>)</code></pre></div>
<p><img src="06-regression_files/figure-html/unnamed-chunk-5-1.png" width="672" /> The output from the regression tree is similar to that from a classification tree. One major difference however is that the predicted values in the end are numeric quantities instead of classes and the probabilities that were shown previously are not shown here as there is not a probability of being in a class. The percentage of cases in the predicted nodes at the end of the tree are still shown. The logic for following the tree is the same as before where each split can have two new paths to follow and then the variable(s) are re-evaluated after the first split to see if additional splits can help predict the outcome of interest.</p>
<p>Below is a figure that builds on the scatterplot we saw above. Vertical lines are shown that indicate the two splits that were established from the above regression tree. These splits are where the end buckets lie and all of the data points residing in a single area have the same predicted log salary.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_point</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>HmRun, <span class="dt">data =</span> Hitters, <span class="dt">color =</span> <span class="st">&#39;gray55&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">gf_vline</span>(<span class="dt">xintercept =</span> <span class="kw">c</span>(<span class="fl">8.5</span>, <span class="dv">19</span>), <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">2</span>, <span class="dt">y =</span> <span class="fl">4.2</span>, <span class="dt">label =</span> <span class="st">&quot;5.6&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">12</span>, <span class="dt">y =</span> <span class="fl">4.2</span>, <span class="dt">label =</span> <span class="st">&quot;6.1&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">32</span>, <span class="dt">y =</span> <span class="fl">4.2</span>, <span class="dt">label =</span> <span class="st">&quot;6.4&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_labs</span>(<span class="dt">y =</span> <span class="st">&quot;Log of player salary&quot;</span>,
            <span class="dt">x =</span> <span class="st">&quot;Number of Home Runs&quot;</span>,
            <span class="dt">title =</span> <span class="st">&quot;Log salary by number of home runs&quot;</span>)</code></pre></div>
<pre><code>## Warning in (function (mapping = NULL, data = NULL, ..., xintercept, na.rm = FALSE, : Using both `xintercept` and `mapping` may not have the desired result as mapping is overwritten if `xintercept` is specified</code></pre>
<p><img src="06-regression_files/figure-html/unnamed-chunk-6-1.png" width="672" /> #### Explore another attribute Let’s explore another attribute, the number of hits in the previous season and how this may be related to the log of the salary. First a scatterplot is shown then the correlation is computed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_point</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>Hits, <span class="dt">data =</span> Hitters)</code></pre></div>
<p><img src="06-regression_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>Hits, <span class="dt">data =</span> Hitters)</code></pre></div>
<pre><code>## [1] 0.4495841</code></pre>
<p>Updating the regression tree with another variable is similar to a classification tree. More than one attribute used to help predict the outcome are separated by <code>+</code> signs. In addition, I specified the model to terminate when the complexity parameter (CP) gets smaller than .012.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hit_reg &lt;-<span class="st"> </span><span class="kw">rpart</span>(<span class="kw">log</span>(Salary) <span class="op">~</span><span class="st"> </span>HmRun <span class="op">+</span><span class="st"> </span>Hits, <span class="dt">data =</span> Hitters, <span class="dt">method =</span> <span class="st">&quot;anova&quot;</span>, <span class="dt">cp =</span> .<span class="dv">012</span>)

<span class="kw">rpart.plot</span>(hit_reg, <span class="dt">roundint =</span> <span class="ot">FALSE</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">branch =</span> .<span class="dv">3</span>)</code></pre></div>
<p><img src="06-regression_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The figure below attempts to show the regression tree in a scatterplot. Now there are more predicted buckets and these are represented by the square areas of the figure below. All of the data points within each square would receive the same predicted score.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_point</span>(HmRun <span class="op">~</span><span class="st"> </span>Hits, <span class="dt">data =</span> Hitters, <span class="dt">color =</span> <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(Salary)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">gf_vline</span>(<span class="dt">xintercept =</span> <span class="kw">c</span>(<span class="dv">118</span>, <span class="dv">146</span>), <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_segment</span>(<span class="fl">8.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">8.5</span> <span class="op">~</span><span class="st"> </span><span class="dv">0</span> <span class="op">+</span><span class="st"> </span><span class="dv">118</span>, <span class="dt">size =</span> <span class="fl">0.75</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_segment</span>(<span class="fl">8.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">8.5</span> <span class="op">~</span><span class="st"> </span><span class="dv">146</span> <span class="op">+</span><span class="st"> </span><span class="dv">238</span>, <span class="dt">size =</span> <span class="fl">0.75</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">1</span>, <span class="dt">y =</span> <span class="dv">3</span>, <span class="dt">label =</span> <span class="st">&quot;5.4&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">128</span>, <span class="dt">y =</span> <span class="dv">3</span>, <span class="dt">label =</span> <span class="st">&quot;6.3&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">170</span>, <span class="dt">y =</span> <span class="dv">3</span>, <span class="dt">label =</span> <span class="st">&quot;6.1&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">50</span>, <span class="dt">y =</span> <span class="dv">35</span>, <span class="dt">label =</span> <span class="st">&quot;5.9&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_text</span>(<span class="dt">x =</span> <span class="dv">200</span>, <span class="dt">y =</span> <span class="dv">35</span>, <span class="dt">label =</span> <span class="st">&quot;6.7&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gf_labs</span>(<span class="dt">x =</span> <span class="st">&quot;Number of Hits&quot;</span>,
            <span class="dt">y =</span> <span class="st">&quot;Number of Home Runs&quot;</span>,
            <span class="dt">title =</span> <span class="st">&quot;Log salary by number of home runs and hits&quot;</span>)</code></pre></div>
<pre><code>## Warning in (function (mapping = NULL, data = NULL, ..., xintercept, na.rm = FALSE, : Using both `xintercept` and `mapping` may not have the desired result as mapping is overwritten if `xintercept` is specified</code></pre>
<p><img src="06-regression_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>One thing that can help with interpretation when the data are transformed, in this case by taking the log of the salary variable, is to back-transform to the original salary metric. In this case, the inverse of the log is the exponential function. This can be achieved in R with the <code>exp()</code> function. The predicted values from the regression tree are back-transformed to show the salaries in their original metric, in thousands of dollars.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(<span class="kw">c</span>(<span class="fl">5.4</span>, <span class="fl">5.9</span>, <span class="fl">6.3</span>, <span class="fl">6.1</span>, <span class="fl">6.7</span>))</code></pre></div>
<pre><code>## [1] 221.4064 365.0375 544.5719 445.8578 812.4058</code></pre>
</div>
<div id="evaluating-accuracy" class="section level3">
<h3><span class="header-section-number">6.1.3</span> Evaluating accuracy</h3>
<p>In the classification tree example, a natural metric to evaluate how well the model was doing was the classification accuracy. This was most useful being computed individually for each class that was predicted instead of solely overall. In the regression tree example, we do not have class membership, instead we have the original observed salary and the predicted salary. One measure that could be used for accuracy is on average how far do the predicted scores deviate from the observed scores. The below code chunk computes those variables for use, one on the log scale and another on the original back-transformed scale.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hitters &lt;-<span class="st"> </span>Hitters <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">log_salary_pred =</span> <span class="kw">predict</span>(hit_reg),
         <span class="dt">log_salary =</span> <span class="kw">log</span>(Salary),
         <span class="dt">log_error =</span> log_salary <span class="op">-</span><span class="st"> </span>log_salary_pred,
         <span class="dt">salary_pred =</span> <span class="kw">exp</span>(log_salary_pred),
         <span class="dt">error =</span> Salary <span class="op">-</span><span class="st"> </span>salary_pred)
<span class="kw">head</span>(Hitters)</code></pre></div>
<pre><code>##   AtBat Hits HmRun Runs RBI Walks Years CAtBat CHits CHmRun CRuns CRBI CWalks
## 1   315   81     7   24  38    39    14   3449   835     69   321  414    375
## 2   479  130    18   66  72    76     3   1624   457     63   224  266    263
## 3   496  141    20   65  78    37    11   5628  1575    225   828  838    354
## 4   321   87    10   39  42    30     2    396   101     12    48   46     33
## 5   594  169     4   74  51    35    11   4408  1133     19   501  336    194
## 6   185   37     1   23   8    21     2    214    42      1    30    9     24
##   League Division PutOuts Assists Errors Salary NewLeague log_salary_pred
## 1      N        W     632      43     10  475.0         N        5.375205
## 2      A        W     880      82     14  480.0         A        6.260120
## 3      N        E     200      11      3  500.0         N        6.260120
## 4      N        E     805      40      4   91.5         N        5.872782
## 5      A        W     282     421     25  750.0         A        6.112038
## 6      N        E      76     127      7   70.0         A        5.375205
##   log_salary   log_error salary_pred      error
## 1   6.163315  0.78810957    215.9842  259.01581
## 2   6.173786 -0.08633342    523.2815  -43.28148
## 3   6.214608 -0.04551143    523.2815  -23.28148
## 4   4.516339 -1.35644260    355.2357 -263.73572
## 5   6.620073  0.50803537    451.2574  298.74263
## 6   4.248495 -1.12670999    215.9842 -145.98419</code></pre>
<p>hen, the <code>df_stats()</code> function is used to compute summary statistics for the <code>log_error</code> attribute which represented the difference between the observed and predicted log salaries. After this, the same statistics are computed for the error after back-transforming the data. Both of these are not quite what we want here, any idea why?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hitters <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>log_error, mean, median, sd, min, max)</code></pre></div>
<pre><code>##   mean_log_error median_log_error sd_log_error min_log_error max_log_error
## 1    1.09754e-15         0.118683    0.7493933     -1.612228      2.287419</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hitters <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span>error, mean, median, sd, min, max)</code></pre></div>
<pre><code>##   mean_error median_error sd_error min_error max_error
## 1   115.4757     34.01581 386.1183  -609.801  1911.349</code></pre>
<p>Instead of computing the average deviation, we first want to take the absolute value of the difference between the observed and predicted scores then compute the summary statistics. This now represents the mean absolute error that was computed earlier when discussing variation and the interpretation of the mean statistic below would be the average distance the predicted scores are from the observed scores, on the log salary scale. In general, lower average distances means the model did a better job of predicting the numeric quantity. However, this value is scale dependent, therefore if the scales of two outcomes are different, the mean absolute error is not directly comparable without some prior standardization.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hitters <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">df_stats</span>(<span class="op">~</span><span class="st"> </span><span class="kw">abs</span>(log_error), mean, median, sd, min, max)</code></pre></div>
<pre><code>##   mean_abs(log_error) median_abs(log_error) sd_abs(log_error)
## 1           0.6128455              0.527838         0.4296245
##   min_abs(log_error) max_abs(log_error)
## 1       0.0002568557           2.287419</code></pre>
</div>
</div>
<div id="simple-regression-continuous-predictor" class="section level2">
<h2><span class="header-section-number">6.2</span> Simple Regression continuous predictor</h2>
<div id="description-of-the-data" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Description of the Data</h3>
<p>These data contain information on mother’s and baby’s health for 1,174 pregnant women.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">baby &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/lebebr01/statthink/master/data-raw/baby.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   birth_weight = col_double(),
##   gestational_days = col_double(),
##   maternal_age = col_double(),
##   maternal_height = col_double(),
##   maternal_pregnancy_weight = col_double(),
##   maternal_smoker = col_logical()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(baby)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   birth_weight gestational_days maternal_age maternal_height maternal_pregna…
##          &lt;dbl&gt;            &lt;dbl&gt;        &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;
## 1          120              284           27              62              100
## 2          113              282           33              64              135
## 3          128              279           28              64              115
## 4          108              282           23              67              125
## 5          136              286           25              62               93
## 6          138              244           33              62              178
## # … with 1 more variable: maternal_smoker &lt;lgl&gt;</code></pre>
</div>
<div id="scatterplots" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Scatterplots</h3>
<p>As we’ve explored before, scatterplots help to explore the relationship between two continuous, quantitative data attributes. These are created with the <code>gf_point()</code> function and adding lines to the figure to provide some guidance to the relationship can be done with the <code>gf_smooth()</code> function. Below, a scatterplot is created that explores the relationship between birth weight and gestational days.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_point</span>(birth_weight <span class="op">~</span><span class="st"> </span>gestational_days, <span class="dt">data =</span> baby, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> .<span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_smooth</span>(<span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="06-regression_files/figure-html/scatter-baby-1.png" width="672" /></p>
<p>The figure shows two types of lines, the dashed line is assuming a linear relationship (specified with <code>gf_smooth(method = 'lm')</code>) and the solid line is allowing the relationship to be more flexible to account for any non-linearity. There does appear to be some evidence of non-linearity, particularly in the tails of gestational days distribution. We can attempt to summarize this relationship in a single numeric value by computing the correlation coefficient. The correlation was initially explored when fitting regression trees. The correlation can be calculated with the <code>cor()</code> function with the primary argument being a formula depicting the two variables to compute the correlation on.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(birth_weight <span class="op">~</span><span class="st"> </span>gestational_days, <span class="dt">data =</span> baby)</code></pre></div>
<pre><code>## [1] 0.4075428</code></pre>
<p>Here the correlation represents the degree of <strong>linear</strong> relationship between the two variables. Values closer to 1 in absolute value (i.e. +1 or -1) show a stronger linear relationship and values closer to 0 indicate no relationship or weaker relationship. The correlation between the two variables above was about 0.41 indicating that there is a moderate positive linear relationship between birth weight and gestational days. The correlation is shown to be positive due to the coefficient being positive and the general trend from the scatterplot shows a direction of relationship moving from the lower left of the figure to the upper right of the figure. A negative correlation would have a negative sign associated with it and would trend from the upper left to the lower right of a scatterplot.</p>
</div>
<div id="fitting-a-linear-regression-model" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Fitting a linear regression model</h3>
<p>Now that the correlation was computed, we have evidence that there is a relationship between the baby birth weight and the gestational days. To provide some more evidence about the strength of this relationship and how much error is involved, fitting a linear regression model is often done. This can be done with the <code>lm()</code> function where the two arguments that need to be specified are a formula and the data to use for the model fitting. The formula takes the following form: <code>birth_weight ~ gestational_days</code>, where birth weight is the outcome of interest (in language we’ve used previously, this is the attribute we want to predict) and gestational days is the attribute we want to use to do the predicting of birth weight. Another way to think about what these variables represent is to explain variation in the birth weight with gestational days. In other words, the assumption is made that gestational days impacts or explains differences in the baby birth weight.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">baby_reg &lt;-<span class="st"> </span><span class="kw">lm</span>(birth_weight <span class="op">~</span><span class="st"> </span>gestational_days, <span class="dt">data =</span> baby)
<span class="kw">coef</span>(baby_reg)</code></pre></div>
<pre><code>##      (Intercept) gestational_days 
##      -10.7541389        0.4665569</code></pre>
<p>he following coefficients represent the linear regression equation that more generally can be show as:</p>
<span class="math display">\[\begin{equation}
birth\_weight = -10.8 + 0.47 gestational\_days + \epsilon
\end{equation}\]</span>
<p>The equation can also be represented without the error, <span class="math inline">\(\epsilon\)</span> as:</p>
<p>begin{equation}  = -10.8 + 0.47 gestational_days \end{equation}</p>
<p>where now the birth weight outcome has a hat (i.e. <span class="math inline">\(\hat{y}\)</span>) that denotes mathematically that the equation predicts a value of birth weight given solely the number of gestational days. The first equation above says that the original observed birth weight is a function of gestational days plus some error. Using the equation above, the predicted birth weight can be obtained by including a value inserted for gestational days. Let’s pick a few values for gestational days to try.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="fl">10.8</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span> <span class="op">*</span><span class="st"> </span><span class="dv">200</span></code></pre></div>
<pre><code>## [1] 83.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="fl">10.8</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span> <span class="op">*</span><span class="st"> </span><span class="dv">275</span></code></pre></div>
<pre><code>## [1] 118.45</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="fl">10.8</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span> <span class="op">*</span><span class="st"> </span><span class="dv">276</span></code></pre></div>
<pre><code>## [1] 118.92</code></pre>
<p>You may notice that the predicted value of birth weight increases by 0.47 grams for every one day increase in gestational days, often referred to as the linear slope. The predicted values would fit on the dashed line shown in the scatterplot shown above. This highlights the assumption made here from the linear regression model above in which the relationship between birth weight and gestational days is assumed to be linear. It is possible to relax this assumption with a more complicated model, however this is the assumption being made currently.</p>
</div>
<div id="explore-the-y-intercept" class="section level3">
<h3><span class="header-section-number">6.2.4</span> Explore the y-intercept</h3>
<p>So far the discussion has focused on the linear slope, often a term that is of most interest. However, the y-intercept can also be made to be more interesting by adjusting the range of gestational days.</p>
<div id="mean-center-gestational-days" class="section level4">
<h4><span class="header-section-number">6.2.4.1</span> Mean center gestational days</h4>
<p>First, mean centering the x attribute can often be a way to make the y-intercept more interpretable. The code below shows a scatterplot by subtracting the mean from all the values of gestational days.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gf_point</span>(birth_weight <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(gestational_days <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(gestational_days)), <span class="dt">data =</span> baby, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> .<span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gf_smooth</span>(<span class="dt">size =</span> <span class="dv">1</span>)</code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="06-regression_files/figure-html/scatter-mean-center-1.png" width="672" /></p>
<p>Notice that the relationship is the same as before, but now the scale of gestational days is different. It may be more difficult to interpret now as the number of days a women is pregnant is relatively well known, but now the mean gestational days is represented as 0 in the figure and all the values are in reference to that instead of referencing when a women became pregnant. Using this same approach, a linear regression can be fitted to this newly recentered gestational days variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">baby_reg_centered &lt;-<span class="st"> </span><span class="kw">lm</span>(birth_weight <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(gestational_days <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(gestational_days)), <span class="dt">data =</span> baby)
<span class="kw">coef</span>(baby_reg_centered)</code></pre></div>
<pre><code>##                                  (Intercept) 
##                                  119.4625213 
## I(gestational_days - mean(gestational_days)) 
##                                    0.4665569</code></pre>
<p>he new equation would look like:</p>
<p>begin{equation}  = 119.5 + 0.47 (gestational_days - mean(gestational_days)) \end{equation}</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">119.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span> <span class="op">*</span><span class="st"> </span><span class="op">-</span><span class="dv">3</span></code></pre></div>
<pre><code>## [1] 118.09</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">119.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span> <span class="op">*</span><span class="st"> </span><span class="dv">0</span></code></pre></div>
<pre><code>## [1] 119.5</code></pre>
</div>
<div id="minimum-or-maximum-centered-gestational-days" class="section level4">
<h4><span class="header-section-number">6.2.4.2</span> Minimum or Maximum centered gestational days</h4>
<p>A few other options that are common are to subtract the minimum or maximum values from the x attribute.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">baby_reg_min &lt;-<span class="st"> </span><span class="kw">lm</span>(birth_weight <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(gestational_days <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(gestational_days)), <span class="dt">data =</span> baby)
<span class="kw">coef</span>(baby_reg_min)</code></pre></div>
<pre><code>##                                 (Intercept) 
##                                  58.2962789 
## I(gestational_days - min(gestational_days)) 
##                                   0.4665569</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">baby_reg_max &lt;-<span class="st"> </span><span class="kw">lm</span>(birth_weight <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(gestational_days <span class="op">-</span><span class="st"> </span><span class="kw">max</span>(gestational_days)), <span class="dt">data =</span> baby)
<span class="kw">coef</span>(baby_reg_max)</code></pre></div>
<pre><code>##                                 (Intercept) 
##                                 153.9404386 
## I(gestational_days - max(gestational_days)) 
##                                   0.4665569</code></pre>
</div>
</div>
</div>
<div id="conditional-means" class="section level2">
<h2><span class="header-section-number">6.3</span> Conditional Means</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="classification.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimation-bootstrap-uncertainty.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
