# stat_thinking

Tentative Title: Statistical Reasoning through Computation and R

# Chapters
1. Introduction    
    a. Statistics vs Data Science    
    b. Experiments vs Observations    
    c. Data Structure     
2. Visualization - univariate (to show syntax), present multivariate (two/three variable) to explore complex questions.    
     a. Explore distributions    
           1. histograms    
           2. density plots    
     b. Conditional (multivariate) distributions    
           1. distribution plots by groups   
           2. violin plots   
           3. Ridge plots?
     c. Scatterplots    
           1. 2d scatterplots    
           2. Add color/shapes    
           3. Label interesting points    
           4. Faceting    
3. Descriptive Statistics / Applying functions to columns of data 
     a. Bring back data structure    
     b. Motivate with data reduction   
     c. Functions to columns of data    
     d. Functions to columns by groups   
     e. Correlation   
4. Classification - move this earlier, more concrete for many students.   
     1. Topic: Decision Trees - bar charts of percentage of correct classification.
         a. performance measures.  
         b. comparison to baseline
             - Absolute vs relative comparison
         c. overfitting.   
         d. cross-validation.     
5. Linear Model    
     a. Simple Regression continuous predictor     
     b. Conditional Means    
     c. Categorical Predictor(s)     
6. Estimation / Bootstrap / Uncertainty      
7. Prediction for individuals    
     a. Comparison of classification / linear model    
8. Compare Assumptions?


# Potentially Axed Chapters
7. Simulation(?)    
8. Sampling vs Empirical Distribution(?) - build into the estimation/bootstrap?  



# Possible Data Sources
- Data from pew research (pew social trends): https://www.pewsocialtrends.org/datasets/
- General Social Survey: https://www.kaggle.com/norc/general-social-survey/
- Gapminder: https://www.gapminder.org/data/
- American Community Survey: Perhaps accessible through tidycensus R package
- Text data based on books: https://www.gutenberg.org/browse/scores/top
- Bike data: https://www.niceridemn.com/system-data
- Animal Bites: https://www.kaggle.com/rtatman/animal-bites
- Lego Database: https://www.kaggle.com/rtatman/lego-database
- Museums: https://www.kaggle.com/imls/museum-directory
- Groundhog day: https://www.kaggle.com/groundhogclub/groundhog-day
- Noise Complaints: https://www.kaggle.com/somesnm/partynyc
- Speed Dating Experiment: https://www.kaggle.com/annavictoria/speed-dating-experiment
- Mosaic R package
- John Hopkins Data Science package.


# Book Themes
- Explore msmbstyle package: https://www-huber.embl.de/msmb/ and https://github.com/grimbough/msmbstyle 

